### PR TITLE
added button to request a new song with same zipcode

### PR DESCRIPTION
**Pull request by jooossshhhh**
The button pretty much just reloads the page using the zip code that was already inputted. Let me know if this solution will work for you or if you want me to come up with a different one.

### CODE REVIEW

**Review by teacherc — COMMENTED** [review]
Hello! I just wanted to let you know that I should have comments back to you (if necessary) by the end of this week.

**Comment by jooossshhhh** [comment]
Sounds good to me, @teacherc !

**Comment by teacherc** [comment]
@jooossshhhh Would it be possible for you to make the button the same size as the player (see image below - the player is off-center). 

Also, any ideas for the copy (text) on the button? I think it could be a bit more descriptive (while staying short - 1-3 words, max). 

Screen Shot 2022-12-15 at 12 21 26 AM

**Comment by teacherc** [comment]
@jooossshhhh Also, I think the button should sit above the edge of the card (there should be padding below it). Right now, it doesn't look like a button until I mouse over it. I think this is due to the sizing.

**Comment by teacherc** [comment]
@jooossshhhh FYI - You could also experiment with putting the button under the card. You can also change the dimensions. Have you tried doing very quick sketches (ovals and boxes)? Curious about your thoughts.

**Comment by jooossshhhh** [comment]
I can experiment with different locations, sizes, and paddings for the button when I get back to the computer with the code on it. I will send you some screenshots with the variations so you can decide on which one looks best. Thanks!

**Comment by jooossshhhh** [comment]
1. Centered, outside card, same button display as 'Ask Spheri'
image
2. Centered, outside card, rectangular border
image
3. Inside card, rectangular border (turned off dark mode for this)
image

4. Same as #3, but uses all properties of 'Ask Spheri' button
image

**Comment by teacherc** [comment]
@jooossshhhh Hello there! I just wanted to thank you for sending these options over. The end of the year has gotten much busier than I thought it would. I will respond by this Sunday with feedback (possibly earlier if I can get a chunk of free time). Happy holidays!

**Comment by jooossshhhh** [comment]
No rush, happy holidays!

**Comment by teacherc** [comment]
@jooossshhhh Hi! Happy New Year! I'm back and will take a look at this very soon. Hope you had a nice holiday season.

**Comment by teacherc** [comment]
Hello @jooossshhhh - 

I just got a new job and am doing a little too much right now. I cannot integrate your changes until I tweak the release system to be a bit more stable (with GitHub Actions). I need to let this project go for now. 

I apologize for the late response.

**Pull request closed without merging**
